#!/bin/bash

# reload scripting addition whenever Dock restarts
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# =================== #
# ===== WINDOWS ===== #
# =================== #
# window layout (bsp, stack or float)
yabai -m config layout bsp
# new windows to the right / bellow
yabai -m config window_placement second_child

# =================== #
# ===== PADDING ===== #
# =================== #
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config right_padding 12
yabai -m config left_padding 12
yabai -m config window_gap 12

# =================== #
# = MOUSE SETTINGS == #
# =================== #
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
# left click
yabai -m config mouse_action1 move
# right click
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# =================== #
# == DISABLED APPS == #
# =================== #
yabai -m rule --add app="^System Settings$" manage=off
# yabai -m rule --add app="^Karabiner-Elements$" manage=off

# sketchybar
yabai -m config external_bar all:32:0

# format
# yabai -m rule --add app="^APP_NAME$" manage=off

# =================== #
# ===== ZATHURA ===== #
# =================== #
yabai -m rule --add app="Zathura" manage=on
yabai -m signal --add event=window_created app="Zathura" action="sleep 0.2; yabai -m window --toggle zoom-fullscreen; yabai -m window --toggle zoom-fullscreen"
yabai -m rule --add app="^zathura$" manage=on
yabai -m signal --add event=window_created app="^zathura$" action="sleep 0.2; yabai -m window --toggle zoom-fullscreen; yabai -m window --toggle zoom-fullscreen"

# jankyborders
borders &
